#!/bin/bash

sudo ./system_backup.sh
sudo cp -rf /boot/config.txt ./boot/config.txt.bak ./boot/config-default.txt ./boot/config-default.txt.bak
sudo cp ./boot/config-default.txt /boot/config.txt
sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt

sudo sync
sudo sync

echo "reboot now"
sudo reboot
